services:
  - type: web
    name: stock-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn stockviewer.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: stockviewer.settings
